name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Run basic tests
        run: |
          echo "✅ No tests yet, pipeline working!"

      - name: Build Docker image
        run: docker build -t flask-devops .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: |
          docker tag flask-devops ${{ secrets.DOCKERHUB_USERNAME }}/flask-devops:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-devops:latest
